// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Sensors
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class IoTSensor : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"IoTSensor\",\"namespace\":\"Sensors\",\"fields\":[{\"name\":\"Sens" +
				"orId\",\"type\":\"string\"},{\"name\":\"Value\",\"type\":\"int\"}]}");
		private string _SensorId;
		private int _Value;
		public virtual Schema Schema
		{
			get
			{
				return IoTSensor._SCHEMA;
			}
		}
		public string SensorId
		{
			get
			{
				return this._SensorId;
			}
			set
			{
				this._SensorId = value;
			}
		}
		public int Value
		{
			get
			{
				return this._Value;
			}
			set
			{
				this._Value = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.SensorId;
			case 1: return this.Value;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.SensorId = (System.String)fieldValue; break;
			case 1: this.Value = (System.Int32)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
