// <auto-generated />

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SqlServer.Connector.Tests.Data;

namespace Kafka.DotNet.SqlServer.Tests.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210707172047_Sensors")]
    partial class Sensors
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Kafka.DotNet.SqlServer.Tests.Data.IoTSensor", b =>
                {
                    b.Property<string>("SensorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("SensorId");

                    b.ToTable("Sensors");
                });
#pragma warning restore 612, 618
        }
    }
}
